name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gsls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/793318155385/locations/global/workloadIdentityPools/github-actions-pool-3/providers/github-actions-provider-3'
          service_account: 'github-actions@healthy-person-emulator.iam.gserviceaccount.com'

      - name: Deploy
        run: |
         gcloud run deploy preview-healthy-person-emulator-dotorg --source . \
          --region=asia-northeast1 \
          --concurrency=1 \
          --memory=2Gi \
          --cpu=2 \
          --timeout=300 \
          --project=healthy-person-emulator \
          --service-account=github-actions@healthy-person-emulator.iam.gserviceaccount.com \
          --verbosity=debug
